import { Heart, Activity, AlertTriangle, Stethoscope, CheckCircle2, HelpCircle, XCircle } from "lucide-react";
import { DiseaseKey, Policy } from "@/types";

export const DISEASES: { value: DiseaseKey; label: string; icon: typeof Heart }[] = [
  { value: "cancer", label: "癌症 Cancer", icon: Activity },
  { value: "cardio", label: "心血管疾病 Cardiovascular", icon: Heart },
  { value: "accident", label: "意外 Accident", icon: AlertTriangle },
  { value: "surgery", label: "手術 Surgery", icon: Stethoscope },
];

export const PAYOUT_META: Record<
  Policy["payoutStandard"],
  { label: string; icon: typeof CheckCircle2; className: string }
> = {
  guaranteed: {
    label: "確定會賠",
    icon: CheckCircle2,
    className: "bg-success/15 text-success border-success/30",
  },
  conditional: {
    label: "可能會理賠",
    icon: HelpCircle,
    className: "bg-warning/15 text-warning border-warning/30",
  },
  consult: {
    label: "需諮詢專員",
    icon: XCircle,
    className: "bg-muted text-muted-foreground border-border",
  },
};

export const MOCK_POLICIES: Policy[] = [
  {
    id: "p1",
    company: "國泰人壽",
    companyEn: "Cathay Life",
    category: "醫療險",
    medicalType: "手術險 Surgery",
    premium: 12800,
    policyName: "康健守護實支實付終身醫療A型",
    description: "涵蓋住院日額、手術費用實支實付，含門診手術、雜費上限每次NT$180,000，保證續保至85歲。",
    payoutAmount: "NT$ 180,000 / 次",
    payoutRatio: "100%",
    payoutStandard: "guaranteed",
  },
  {
    id: "p2",
    company: "南山人壽",
    companyEn: "Nan Shan Life",
    category: "重大疾病",
    medicalType: "癌症險 Cancer",
    premium: 18500,
    policyName: "新一代抗癌鬥士終身癌症保險",
    description: "初次罹癌一次金NT$1,000,000，化療放療每次給付，含標靶藥物與癌症門診手術。",
    payoutAmount: "NT$ 1,000,000",
    payoutRatio: "100%",
    payoutStandard: "guaranteed",
    flagged: {
      source: "Dcard 保險版 2024/06 討論串",
      note: "多名用戶反映理賠審核期較長，部分標靶藥物需附加證明。",
    },
  },
  {
    id: "p3",
    company: "富邦人壽",
    companyEn: "Fubon Life",
    category: "意外險",
    medicalType: "意外險 Accident",
    premium: 4200,
    policyName: "全方位意外傷害保險 Plus",
    description: "意外身故最高NT$3,000,000，意外醫療實支實付上限NT$60,000，含交通事故加倍給付。",
    payoutAmount: "NT$ 60,000 / 次",
    payoutRatio: "90%",
    payoutStandard: "conditional",
  },
  {
    id: "p4",
    company: "新光人壽",
    companyEn: "Shin Kong Life",
    category: "醫療險",
    medicalType: "住院醫療 Hospitalization",
    premium: 9800,
    policyName: "安心醫定保住院日額醫療",
    description: "住院日額NT$3,000，加護病房加倍，含門診手術，保證續保至75歲。",
    payoutAmount: "NT$ 3,000 / 日",
    payoutRatio: "80%",
    payoutStandard: "conditional",
  },
  {
    id: "p5",
    company: "遠雄人壽",
    companyEn: "Yuanta Life",
    category: "重大疾病",
    medicalType: "心血管險 Cardio",
    premium: 15200,
    policyName: "護心心血管重大傷病保障",
    description: "涵蓋7項心血管重大傷病一次金NT$800,000，含心導管手術與支架植入。",
    payoutAmount: "NT$ 800,000",
    payoutRatio: "100%",
    payoutStandard: "guaranteed",
    flagged: {
      source: "PTT insurance 版 2023 熱門文",
      note: "早期版本條款對「心血管重大傷病」定義較嚴格，需諮詢最新版本。",
    },
  },
  {
    id: "p6",
    company: "中國人壽",
    companyEn: "China Life",
    category: "醫療險",
    medicalType: "實支實付 Reimbursement",
    premium: 11600,
    policyName: "雙實付優選醫療終身保險",
    description: "雜費、手術費、住院日額三擇一給付，每次事故上限NT$200,000，可副本理賠。",
    payoutAmount: "NT$ 200,000 / 次",
    payoutRatio: "100%",
    payoutStandard: "guaranteed",
  },
  {
    id: "p7",
    company: "三商美邦",
    companyEn: "Mercuries Life",
    category: "意外險",
    medicalType: "意外醫療 Accident Med",
    premium: 3600,
    policyName: "平安守護意外傷害醫療附約",
    description: "意外醫療實支實付NT$30,000/次，含骨折未住院日額給付。",
    payoutAmount: "NT$ 30,000 / 次",
    payoutRatio: "70%",
    payoutStandard: "consult",
  },
  {
    id: "p8",
    company: "全球人壽",
    companyEn: "Transglobe Life",
    category: "重大疾病",
    medicalType: "癌症險 Cancer",
    premium: 13400,
    policyName: "抗癌保庇一年期癌症醫療",
    description: "癌症住院日額NT$5,000，癌症手術給付，可依病程續保。",
    payoutAmount: "NT$ 5,000 / 日",
    payoutRatio: "85%",
    payoutStandard: "conditional",
  },
  {
    id: "p9",
    company: "台灣人壽",
    companyEn: "Taiwan Life",
    category: "醫療險",
    medicalType: "手術險 Surgery",
    premium: 10800,
    policyName: "手術金保障終身醫療險",
    description: "涵蓋2000+手術項目，門診手術亦給付，最高倍數20倍。",
    payoutAmount: "NT$ 150,000 / 次",
    payoutRatio: "95%",
    payoutStandard: "guaranteed",
  },
  {
    id: "p10",
    company: "宏泰人壽",
    companyEn: "Hontai Life",
    category: "醫療險",
    medicalType: "住院日額 Hospital",
    premium: 7200,
    policyName: "健康Plus住院日額醫療",
    description: "住院日額NT$2,000，含癌症住院加倍，可搭配實支實付使用。",
    payoutAmount: "NT$ 2,000 / 日",
    payoutRatio: "75%",
    payoutStandard: "consult",
    flagged: {
      source: "Mobile01 保險討論區",
      note: "部分用戶反映客服回應速度較慢，理賠文件要求較繁瑣。",
    },
  },
];